### ISSUE TITLE
As a student, I want to see my followers, so that I can see all of the other students who follow me

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#104]
**User Story:**
As a student, I want to see my followers, so that I can see all of the other students who follow me

**Description**
We will allow students to see all the other students who follow them.

**Acceptance Criteria**
- Students should be able to see who follows them
- Students must be logged into their account in order to see their followers

**Testing**
- We will test to make sure the user is logged in to be able to see their followers

**Comment by marceljar** [comment]
Accepted.
Mostly a display functionality.

**Comment by marceljar** [comment]
Fully implemented.
