### ISSUE TITLE
As a student, I want to reply to comments on posts, so that I can let the author of the comment know my thoughts about it

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#105]
**User Story:**
As a student, I want to reply to comments on posts, so that I can let the author of the comment know my thoughts about it

**Description**
We will use and add a system for replying to comments on posts. This system will allow the user to reply on either their own comment or other comments. It will include the time at which it was posted, by whom, the content, and an indicator that it is replying to another comment.

**Acceptance**
- User should be able to reply on anyone's comment.

**Testing**
- Test to see if the reply is indicating the correct comment
- Test to see if the reply is seen by others and not only the poster.
- Test to see if multiple replies work.

**Comment by marceljar** [comment]
Accepted.
Details still TBD.

**Comment by marceljar** [comment]
Fully implemented.
