### ISSUE TITLE
As a student, I want to edit my profile, so that I can display any information I want about me

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#13]
**User Story:**
As a student, I want to edit my profile, so that I can display any information I want about me.

**Description**
We will allow students to edit particular information about their profile as a form. Once the form is submitted, the MongoDB database will update the student's profile internally and display the changes visually. Students can optionally edit many parts of their profile, some include their bio, full name, and profile picture. More options like birth date, contact information, location...etc. may be implemented later.

**Acceptance Criteria**
- Students should be able to edit many parts of their profile
- When requesting to edit a profile, the student is redirected to an "Edit your Profile" page
- Adding information like bio, name, and profile picture should be optional
- Students must be logged into their account in order to edit their profile

**Testing**
- We will test getting profile information using a valid account 
- We will test editing a student profile under the flexibility of having students optionally choose what they want to show

**Comment by marceljar** [comment]
Accepted. Users should also be able to choose if their profile is private or public. When clicking on a private profile (from a comment, for example) a message that that profile is private will be shown.
