### ISSUE TITLE
As a student, I want to comment on posts, so that I can let the author know my thoughts about it

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#15]
**User Story:**
As a student, I want to comment on posts, so that I can let my follower know my thoughts are on their post.

**Description**
We will use and add a system for commenting on posts. This system will allow the user to comment on either their own posts
or others. It will include the time at which it was posted, by whom, and the content.

**Acceptance**
- User should be able to comment on anyone's posts.

**Testing**
- Test to see if the comment is placed on the correct post.
- Test to see if the comment is seen by others and not only the poster.
- Test to see if multiple comments work.

**Comment by marceljar** [comment]
- Once posted, a comment cannot be edit (for now)
- One thread, figure out how to make it obivous when a user is replying to a previous comment, rather than to the post itself.

**Comment by marceljar** [comment]
Completed.
