### ISSUE TITLE
As a student, I want to like posts, so that I can let my friends know I enjoyed their post

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#19]
**User Story:**
As a student, I want to like posts, so that I can let my friends know I enjoyed their post

**Description**
We will use and add a system for liking a post. This system will allow the user to like other students posts

**Acceptance**
- User should be able to like the students post.

**Testing**
- Test to see if the like is added on the correct post.
- Test to see if the like is seen by others and not only the poster.

**Comment by marceljar** [comment]
- Make sure that each user can only like a post once.
- Users should be able to cancel their like
- Full-stack

**Comment by marceljar** [comment]
Completed!
