### ISSUE TITLE
As a student, I want to see my profile, so that I can see the information i've added to my profile

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#54]
**User Story:**
As a student, I want to see my profile, so that I can see the information i've added to my profile

**Description**
We will allow students to see the information they added to their profile such as their profile pic, username, bio, etc.

**Acceptance Criteria**
- Students should be able to see their profile
- Adding information like bio, name, and profile picture should be optional
- Students must be logged into their account in order to see their profile

**Testing**
- We will test getting profile information using a valid account

**Comment by marceljar** [comment]
Completed!
