### ISSUE TITLE
As a student, I want to see other students profiles, so that I can learn more information about them

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#67]
**User Story:**
As a student, I want to see other students profiles, so that I can learn more information about them

**Description**
We will allow students to see other students profiles. We will also add the ability to follow the other student.

**Acceptance Criteria**
- Students should be able to see other students profiles

**Testing**
- We will test getting other students profile information using a valid account 
- We will test editing a student profile under the flexibility of having students optionally choose what they want to show
- Students must be logged into their account in order to see other students profile

**Comment by marceljar** [comment]
Accepted. Make sure to add a few realistic profiles to the system to showcase this use case.
