### ISSUE TITLE
As a developer, I want to improve the app, so that I can give the users of the app a better experience

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#68]
**User Story:**
As a developer, I want to improve the app, so that I can give the users of the app a better experience

**Description**
We want to provide UI enhancements, more bug fixes, extra input and error validation to prevent adding an empty comment and prevent posting content without an image or caption. We also want to improve the flow of the app by providing dynamic like, delete post, and delete comment.

**Acceptance Criteria**
- The app is updated and provides students with a better experience

**Testing**
- We will test the newly improved app by logging in to one of our test student accounts to see the app through their eyes

**Comment by marceljar** [comment]
Accepted.

**Comment by marceljar** [comment]
Still seems to require a refresh. Try to figure out ways to dynamically update jsut the element that has changed. As it is 9/10 for this sprint. If fixed by Sprint Planning 3, Full marks.

**Comment by marceljar** [comment]
- Add date and time for posts
- Create a more polished and coherent UI (using Angular and Material)
