### ISSUE TITLE
As a student, I want to see my posts on my profile, so that I can see all the posts that i've posted myself

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#81]
**User Story:**
As a student, I want to see my posts on my profile, so that I can see all the posts that i've posted myself

**Description**
We will allow students to see all the posts they've posted in their profile tab 

**Acceptance Criteria**
- Students should be able to see their posts on their profile
- Students must be logged into their account in order to see their profile and their posts

**Testing**
- We will test getting profile information using a valid account
- We will test by switching between accounts to make sure the posts are theirs for each users profile
- We will test the posts to make sure that the posts showing are the users posts

**Comment by marceljar** [comment]
Accepted.
- Accessible via a new item in the navbar
