### ISSUE TITLE
As a developer, I want to change the time format, so that all post dates and comment dates are in EST format

### ISSUE THREAD

**Issue by Nate-K0** [Nate-K0/SeneConnectApp#83]
**User Story:**
As a developer, I want to change the time format, so that all post dates and comment dates are in EST format

**Description**
We will change the time format for posts and comments to show in a clear EST date format, for example. 8:30am EST.

**Acceptance Criteria**
- Date format should be changed to a EST format

**Testing**
- We will test by checking if the date format worked
- We will test by making sure that any new posts and comments will use the new date format

**Comment by marceljar** [comment]
Accepted.
So, posts should have timestamps such as "March 23rd, 2023 - 8:00 PM EST"
